name: CI
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release version
        id: release
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test output
        run: |
          echo 'Exists ${{steps.release.outputs.release_exists}}'
          echo 'Created ${{steps.release.outputs.release_created}}'
          echo 'Tag ${{steps.release.outputs.release_tag}}'
          echo 'Release context: ${{steps.version.outputs.release_context}}'
      - name: Test condition exists
        if: steps.release.outputs.release_exists
        run: |
          echo '${{steps.release.outputs.release_exists == true}}'
          echo '${{steps.release.outputs.release_exists == 'true'}}'
      - name: Test condition created
        if: steps.release.outputs.release_created
        run: |
          echo '${{steps.release.outputs.release_created == true}}'
          echo '${{steps.release.outputs.release_created == 'true'}}'
